environments:
  systemtest-conexus:
    pipelines:
      - moe-webinar-build
      - moe-webinar-deploy
format_version: 3
pipelines:
  moe-webinar-build:
    group: moe-webinar
    lock_behavior: none
    materials:
      github-git:
        branch: master
        git: "https://github.com/osd-henry/test-docker.git"
        destination: source
    stages:
      -
        test-local-docker-build:
          jobs:
            test-local-docker-build:
              resources:
                - linux-build
              tasks:
                -
                  script: |-
                      cd source
                      sudo bash ./scripts/build.sh
              artifacts:
                - build:
                    source: source
                    destination: built_artifacts
  moe-webinar-deploy:
    group: moe-webinar
    lock_behavior: none
    materials:
      upstream: 
        pipeline: moe-webinar-build
        stage: test-local-docker-build
    label_template: "${upstream}"
    stages:
      -
        run-deploy-script:
          jobs:
            run-deploy-script:
              run_instances: all
              resources:
                - linux-deploy
              artifacts:
                - build:
                    source: source
              tasks:
                -
                  fetch:
                    pipeline: moe-webinar-build
                    stage: test-local-docker-build
                    job: test-local-docker-build
                    source: built_artifacts
                    destination: source
                  run_if: passed
                -
                  script: |-
                      echo "List artifacts:"
                      ls source | grep "s/^/ - /"
                      echo "---"
                      cd source/built_artifacts
                      ./scripts/deploy.sh git@github.com:osd-henry/test-docker.git --to root@104.248.157.25 --into-folder app --using-rsa-key /var/go/.ssh/webminar_id_rsa
                  run_if: passed