environments:
  systemtest-conexus:
    pipelines:
      - moe-webinar-build
      - moe-webinar-deploy
format_version: 3
pipelines:
  moe-webinar-build:
    group: moe-webinar
    lock_behavior: none
    materials:
      github-git:
        branch: master
        git: "https://github.com/osd-henry/test-docker.git"
        destination: source
    stages:
      -
        test-local-docker-build:
          jobs:
            test-local-docker-build:
              resources:
                - linux-build
              tasks:
                -
                  script: |-
                      cd source
                      sudo bash ./scripts/build.sh
              artifacts:
                - build:
                    source: source
                    destination: built_artifacts
  moe-webinar-deploy:
    group: moe-webinar
    lock_behavior: none
    materials:
      upstream: 
        pipeline: moe-webinar-build
        stage: test-local-docker-build
    label_template: "${upstream}"
    stages:
      -
        run-deploy-script:
          jobs:
            run-deploy-script:
              run_instances: all
              resources:
                - linux-deploy
              tasks:
                -
                  fetch:
                    pipeline: moe-webinar-build
                    stage: test-local-docker-build
                    job: test-local-docker-build
                    source: built_artifacts
                  run_if: passed
                -
                  script: |-
                      cd built_artifacts/source
                      sudo docker-compose down
                  run_if: passed