environments:
  moe-webinar-release:
    pipelines:
      - moe-webinar-build
      - moe-webinar-deploy
format_version: 3
pipelines:
  moe-webinar-build:
    lock_behavior: none
    materials:
      github-git:
        branch: master
        git: "https://github.com/osd-henry/test-docker.git"
        destination: source
    stages:
      -
        test-local-docker-build:
          jobs:
            prepare-build:
              # resources:
              #   - linux-build
              tasks:
                -
                  script: |-
                      ./scripts/build.sh
  moe-webinar-deploy:
    lock_behavior: none
    materials:
      upstream:
        pipeline: moe-webinar-build
        stage: test-docker-deploy
    label_template: "${upstream}"
    stages:
      -
        run-deploy-script:
          fetch_materials: no
          jobs:
            run-deploy-script:
              run_instances: all
              # resources:
              #   - win-deploy
              # artifacts:
              #   - build:
              #       source: source
              tasks:
                -
                  script: |-
                      ./scripts/deploy.sh git@github.com:osd-henry/test-docker.git --to root@104.248.157.25 --into-folder app --using-rsa-key ~/.ssh/cxs-gocd-rsa
                  run_if: passed