environments:
  systemtest-conexus:
    pipelines:
      - moe-webinar-build
      - moe-webinar-deploy
format_version: 3
pipelines:
  moe-webinar-build:
    group: moe-webinar
    lock_behavior: none
    materials:
      github-git:
        branch: master
        git: "https://github.com/osd-henry/test-docker.git"
        destination: source
    stages:
      -
        test-local-docker-build:
          jobs:
            test-local-docker-build:
              resources:
                - linux-build
              tasks:
                -
                  script: |-
                      cd source
                      sudo bash ./scripts/build.sh
      -
        push-artifacts:
          jobs:
            push-artifacts:
              resources:
                - linux-build
              tasks:
                -
                  script: |-
                      cd source
                      sudo bash ./scripts/build_artifacts.sh
                  run_if: passed
              artifacts:
                - build:
                    source: source/artifacts
                    destination: source
  moe-webinar-deploy:
    group: moe-webinar
    lock_behavior: none
    materials:
      upstream:
        pipeline: moe-webinar-build
        stage: push-artifacts
    label_template: "${upstream}"
    stages:
      -
        fetch-deploy-files:
          jobs:
            fetch-deploy-files:
              run_instances: all
              resources:
                - linux-deploy
              tasks:
                -
                  fetch:
                    pipeline: moe-webinar-build
                    stage: push-artifacts
                    job: push-artifacts
                    source: source
                  run_if: passed
      -
        run-deploy-script:
          fetch_materials: no
          jobs:
            run-deploy-script:
              run_instances: all
              resources:
                - linux-deploy
              artifacts:
                - build:
                    source: source
                    destination: deploy
              tasks:
                -
                  script: |-
                      ./deploy/scripts/deploy.sh git@github.com:osd-henry/test-docker.git --to root@104.248.157.25 --into-folder app --using-rsa-key /var/go/.ssh/webminar_id_rsa
                  run_if: passed